server:
  port: 10880
guanweiming:
  s3:
    enabled: true
    access-key: 1
    bucket: 1
    secret-key: 1
    url: 1
  weblog:
    enabled: true
proxy:
  client-key: 6a500c3294fe4dd7b18440b65fada93d
  server-port: 4900
  server-host: coding-space.cn
  ssl-enable: false
<<<<<<< HEAD
grpc:
  server:
    port: 0
=======
springfox:
  documentation:
    swagger-ui:
      base-url: /doc
>>>>>>> 732c9fc (netty)
