server:
  port: 8888
guanweiming:
  s3:
    enabled: true
    access-key: 1
    bucket: 1
    secret-key: 1
    url: 1
  weblog:
    enabled: true
proxy:
  client-key: 779d65c71c6d42318a6bdae0d7d20f55
  server-port: 4900
  server-host: redis.coding-space.cn
  ssl-enable: false
grpc:
  server:
    port: 0
